name: Azure VM Deployment Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Code via SSH to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            echo "Successfully connected to Azure VM Server!"
            sudo apt-get update -y
            sudo apt-get install -y docker.io git
            
            # Purana folder delete karke fresh code pull karenge
            rm -rf polyglot-devops-project
            
            # Fresh clone from your repository
            git clone https://github.com/243459-del/polyglot-devops-project.git
            
            echo "Deployment Completed Successfully on Azure Cloud Machine!"
